#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))
    total_sum_hourglass= -100
    for i in range(1,5):
        for j in range (1,5):
            sum_hourglass=arr[i][j]+arr[i-1][j-1]+arr[i-1][j]+arr[i-1][j+1]+arr[i+1][j-1]+arr[i+1][j]+arr[i+1][j+1]
            if total_sum_hourglass < sum_hourglass:
                total_sum_hourglass = sum_hourglass
    
    print (total_sum_hourglass)

