#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        result = 0
        nk = input().split()
        n = int(nk[0])
        k = int(nk[1])

        for i in range(1,n+1):
            for j in range (1,n+1):
                if int(i)==int(j):
                    break
    
                elif int(i & j) > result and int(i& j) < k :
                    
                    result = int(i&j)
        print (result) 
                 
