#!/bin/python3

import sys

n = int(input().strip())
a = list(map(int, input().strip().split(' ')))
numSwaps = 0
for i in range(1,1+n):
    for j , value in enumerate (a) :
        if j < n - 1 :
            if a[j] > a[j+1]:
                a[j], a[j + 1] = a[j+1] , a[j]
                numSwaps = numSwaps + 1

print ("Array is sorted in " + str(numSwaps) +" swaps.")
print ("First Element: " +str(a[0]))
print ("Last Element: "+ str(a[n-1]))

